version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"

  mystorecontrol:
    container_name: mystorecontrol
    labels:
      NAME: "mystorecontrol"
    build:
      context: .
      dockerfile: src/MyStoreControl/Dockerfile
    networks:
      my_network:
    ports:
      - "5001:80"

  mystoresale:
    container_name: mystoresale
    build:
      context: .
      dockerfile: src/MyStoreSale/Dockerfile
    networks:
      my_network:
    ports:
      - "5011:80"

networks:
  my_network: